### ISSUE TITLE
Uncaught Error: Could not find module `ember-new-computed` imported from {{addon-name}}

### ISSUE THREAD

**Issue by igorrKurr** [rwjblue/ember-new-computed#5]
Hi!

I was using `ember-cli-selectize` when this error appeared:

```
Uncaught Error: Could not find module `ember-new-computed` imported from `ember-cli-selectize/components/ember-selectize`
```

(You can related discussion there - https://github.com/miguelcobain/ember-cli-selectize/issues/69)

After trying to reinstall packages, i created new app and new addon to reproduce this issue (if you will need them pls tell and i push them) and this issue appeared again.

Maybe this is more ember-cli-stuff, not this addon, but pls, take look at it.

**Comment by Frozenfire92** [comment]
+1 Also ran into this today

**Comment by Frozenfire92** [comment]
@igorrKurr it would probably speed things up if you were able to push your app up that demonstrates this bug

**Comment by igorrKurr** [comment]
Sure!

This is for addon where i used `ember-new-computed`: https://github.com/igorrKurr/ember-new-computed-example-addon (main points here are: https://github.com/igorrKurr/ember-new-computed-example-addon/blob/master/addon/components/return-str.js)
And this for app where i used addon: https://github.com/igorrKurr/ember-new-computed-example-app (main points - https://github.com/igorrKurr/ember-new-computed-example-app/blob/master/app/templates/application.hbs#L3)

**Comment by rwjblue** [comment]
What is the output for `npm --version`, `node --version`, `ember version`?  Also, what version of ember-cli-babel are you using in your project?

**Comment by igorrKurr** [comment]
For each addon and app:

```
ember version
Future versions of Ember CLI will not support v0.10.36. Please update to Node 0.12 or io.js.
version: 0.2.5
0.2.5

node: 0.10.36
npm: 2.10.0
```

```
node --version
v0.10.36
```

```
npm --version
1.4.28
```

```
npm list ember-cli-babel
try-comp-addon@0.0.0 /Users/igor/projects/try-comp-addon
├── ember-cli-babel@5.0.0
└─┬ try-comp@0.0.1 -> /Users/igor/projects/try-comp
  ├── ember-cli-babel@5.0.0
  ├─┬ ember-disable-prototype-extensions@1.0.1
  │ └── ember-cli-babel@4.3.3
  └─┬ ember-new-computed@1.0.0
    └── ember-cli-babel@4.3.3
```

**Comment by HeroicEric** [comment]
Same issue. Here's my info if it helps:

```
$ ember --version
version: 0.2.5
node: 2.0.0 (io.js)
npm: 2.10.0

ember-cli-babel   "version": "5.0.0",
babel-core   "version": "5.4.4",
```

**Comment by Frozenfire92** [comment]
npm: 2.7.1
node: v0.12.0

```
ember version
version: 0.2.5
0.2.5

node: 0.12.0
npm: 2.10.0
```

`"ember-cli-babel": "^5.0.0",`

UPDATE: Also using Ember 1.12.0

**Comment by Frozenfire92** [comment]
This has been fixed in ember-cli-selectize v0.3.3 see https://github.com/miguelcobain/ember-cli-selectize/issues/69

**Comment by igorrKurr** [comment]
In `ember-cli-selectize` they just stop using `ember-new-computed` so issue is still actual.

**Comment by jacobq** [comment]
I'm guessing this can be closed now ;)
